import type { Calculator } from '../types';

/** Glasgow Koma Skalası (GKS). */
export const gcs: Calculator = {
  id: 'gcs',
  category: 'neuro',
  code: 'GKS',
  kind: 'additive',
  max: 15,
  name: { tr: 'Glasgow Koma Skalası', az: 'Qlazqo Koma Şkalası', 'tr-CY': 'Glasgow Koma Skalası' },
  subtitle: { tr: 'Bilinç düzeyi', az: 'Şüur səviyyəsi', 'tr-CY': 'Bilinç düzeyi' },
  use: {
    tr: 'Travma ve akut nörolojik durumlarda bilinç düzeyini standardize biçimde ölçer ve seri takibe olanak tanır.',
    az: 'Travma və kəskin nevroloji vəziyyətlərdə şüur səviyyəsini standart şəkildə ölçür və seriyalı izləməyə imkan verir.',
    'tr-CY': 'Travma ve akut nörolojik durumlarda bilinç düzeyini standardize biçimde ölçer ve seri takibe olanak tanır.',
  },
  evidence: {
    tr: 'Teasdale & Jennett, 1974. Uluslararası standart bilinç değerlendirme aracı.',
    az: 'Teasdale & Jennett, 1974. Beynəlxalq standart şüur qiymətləndirmə vasitəsi.',
    'tr-CY': 'Teasdale & Jennett, 1974. Uluslararası standart bilinç değerlendirme aracı.',
  },
  metricLabel: { tr: 'Bilinç bozukluğu', az: 'Şüur pozğunluğu', 'tr-CY': 'Bilinç bozukluğu' },
  inputs: [
    { id: 'eye', type: 'single', default: 4,
      label: { tr: 'Göz açma', az: 'Göz açma', 'tr-CY': 'Göz açma' },
      options: [
        { value: 1, points: 1, label: { tr: 'Yok', az: 'Yox', 'tr-CY': 'Yok' } },
        { value: 2, points: 2, label: { tr: 'Ağrıyla', az: 'Ağrıyla', 'tr-CY': 'Ağrıyla' } },
        { value: 3, points: 3, label: { tr: 'Sesle', az: 'Səslə', 'tr-CY': 'Sesle' } },
        { value: 4, points: 4, label: { tr: 'Spontan', az: 'Spontan', 'tr-CY': 'Spontan' } },
      ] },
    { id: 'verbal', type: 'single', default: 5,
      label: { tr: 'Sözel yanıt', az: 'Nitq cavabı', 'tr-CY': 'Sözel yanıt' },
      options: [
        { value: 1, points: 1, label: { tr: 'Yok', az: 'Yox', 'tr-CY': 'Yok' } },
        { value: 2, points: 2, label: { tr: 'Sesler', az: 'Səslər', 'tr-CY': 'Sesler' } },
        { value: 3, points: 3, label: { tr: 'Kelimeler', az: 'Sözlər', 'tr-CY': 'Kelimeler' } },
        { value: 4, points: 4, label: { tr: 'Konfüze', az: 'Çaşqın', 'tr-CY': 'Konfüze' } },
        { value: 5, points: 5, label: { tr: 'Oryante', az: 'Oriyentasiyalı', 'tr-CY': 'Oryante' } },
      ] },
    { id: 'motor', type: 'single', default: 6,
      label: { tr: 'Motor yanıt', az: 'Motor cavabı', 'tr-CY': 'Motor yanıt' },
      options: [
        { value: 1, points: 1, label: { tr: 'Yok', az: 'Yox', 'tr-CY': 'Yok' } },
        { value: 2, points: 2, label: { tr: 'Ekstansiyon', az: 'Ekstensiya', 'tr-CY': 'Ekstansiyon' } },
        { value: 3, points: 3, label: { tr: 'Anormal fleksiyon', az: 'Anormal fleksiya', 'tr-CY': 'Anormal fleksiyon' } },
        { value: 4, points: 4, label: { tr: 'Çekme', az: 'Çəkilmə', 'tr-CY': 'Çekme' } },
        { value: 5, points: 5, label: { tr: 'Lokalize', az: 'Lokalizə', 'tr-CY': 'Lokalize' } },
        { value: 6, points: 6, label: { tr: 'Emir uyar', az: 'Əmrə tabe', 'tr-CY': 'Emir uyar' } },
      ] },
  ],
  bands: [
    { min: 13, max: 15, tone: 'low',
      riskLabel: { tr: 'Hafif', az: 'Yüngül', 'tr-CY': 'Hafif' },
      metric: { tr: 'Hafif', az: 'Yüngül', 'tr-CY': 'Hafif' },
      advice: { tr: 'Hafif kafa travması; gözlem.', az: 'Yüngül kəllə travması; müşahidə.', 'tr-CY': 'Hafif kafa travması; gözlem.' } },
    { min: 9, max: 12, tone: 'mid',
      riskLabel: { tr: 'Orta', az: 'Orta', 'tr-CY': 'Orta' },
      metric: { tr: 'Orta', az: 'Orta', 'tr-CY': 'Orta' },
      advice: { tr: 'Yakın izlem; görüntüleme gerekebilir.', az: 'Yaxın izləmə; görüntüləmə lazım ola bilər.', 'tr-CY': 'Yakın izlem; görüntüleme gerekebilir.' } },
    { min: 3, max: 8, tone: 'high',
      riskLabel: { tr: 'Ağır', az: 'Ağır', 'tr-CY': 'Ağır' },
      metric: { tr: 'Ağır', az: 'Ağır', 'tr-CY': 'Ağır' },
      advice: { tr: '≤8: havayolu güvenliği, entübasyon düşün.', az: '≤8: hava yolu təhlükəsizliyi, intubasiya düşün.', 'tr-CY': '≤8: havayolu güvenliği, entübasyon düşün.' } },
  ],
  references: ['Teasdale G, Jennett B. Assessment of coma and impaired consciousness. Lancet. 1974.'],
};
