import type { Calculator } from '../types';

/** Wells Skoru — Pulmoner Emboli (PE) klinik olasılığı. */
export const wells: Calculator = {
  id: 'wells',
  category: 'pulm',
  code: 'Wells',
  kind: 'additive',
  max: 12.5,
  name: { tr: 'Wells Skoru (PE)', az: 'Wells Balı (PE)', 'tr-CY': 'Wells Skoru (PE)' },
  subtitle: { tr: 'Pulmoner emboli olasılığı', az: 'Pulmoner emboliya ehtimalı', 'tr-CY': 'Pulmoner emboli olasılığı' },
  use: {
    tr: 'Pulmoner emboli şüphesi olan hastalarda klinik ön-test olasılığını belirler; D-dimer veya BT anjiyografi kararını yönlendirir.',
    az: 'Pulmoner emboliya şübhəsi olan xəstələrdə klinik öncə-test ehtimalını müəyyən edir; D-dimer və ya KT anjioqrafiya qərarını yönləndirir.',
    'tr-CY': 'Pulmoner emboli şüphesi olan hastalarda klinik ön-test olasılığını belirler; D-dimer veya BT anjiyografi kararını yönlendirir.',
  },
  evidence: {
    tr: 'Wells ve ark., 2000. Geniş kohortlarda valide edilmiş ön-test olasılık skoru.',
    az: 'Wells və ark., 2000. Geniş kohortlarda validə edilmiş öncə-test ehtimal balı.',
    'tr-CY': 'Wells ve ark., 2000. Geniş kohortlarda valide edilmiş ön-test olasılık skoru.',
  },
  metricLabel: { tr: 'Klinik olasılık', az: 'Klinik ehtimal', 'tr-CY': 'Klinik olasılık' },
  inputs: [
    { id: 'dvt', type: 'boolean', points: 3,
      label: { tr: 'DVT klinik bulguları', az: 'DVT klinik əlamətləri', 'tr-CY': 'DVT klinik bulguları' },
      hint: { tr: 'Bacakta şişlik, ağrı', az: 'Ayaqda şişkinlik, ağrı', 'tr-CY': 'Bacakta şişlik, ağrı' } },
    { id: 'alt', type: 'boolean', points: 3,
      label: { tr: 'PE en olası tanı', az: 'PE ən ehtimallı diaqnoz', 'tr-CY': 'PE en olası tanı' },
      hint: { tr: 'Alternatif daha az olası', az: 'Alternativ daha az ehtimallı', 'tr-CY': 'Alternatif daha az olası' } },
    { id: 'hr', type: 'boolean', points: 1.5,
      label: { tr: 'Kalp hızı > 100/dk', az: 'Ürək döyüntüsü > 100/dəq', 'tr-CY': 'Kalp hızı > 100/dk' },
      hint: { tr: 'Taşikardi', az: 'Taxikardiya', 'tr-CY': 'Taşikardi' } },
    { id: 'immob', type: 'boolean', points: 1.5,
      label: { tr: 'İmmobilizasyon / cerrahi', az: 'İmmobilizasiya / cərrahiyyə', 'tr-CY': 'İmmobilizasyon / cerrahi' },
      hint: { tr: 'Son 4 haftada', az: 'Son 4 həftədə', 'tr-CY': 'Son 4 haftada' } },
    { id: 'prev', type: 'boolean', points: 1.5,
      label: { tr: 'Önceki PE / DVT', az: 'Əvvəlki PE / DVT', 'tr-CY': 'Önceki PE / DVT' },
      hint: { tr: 'Öyküde mevcut', az: 'Anamnezdə var', 'tr-CY': 'Öyküde mevcut' } },
    { id: 'hemo', type: 'boolean', points: 1,
      label: { tr: 'Hemoptizi', az: 'Hemoptiz', 'tr-CY': 'Hemoptizi' },
      hint: { tr: 'Kanlı balgam', az: 'Qanlı bəlğəm', 'tr-CY': 'Kanlı balgam' } },
    { id: 'malig', type: 'boolean', points: 1,
      label: { tr: 'Malignite', az: 'Malignite', 'tr-CY': 'Malignite' },
      hint: { tr: 'Son 6 ayda tedavi', az: 'Son 6 ayda müalicə', 'tr-CY': 'Son 6 ayda tedavi' } },
  ],
  bands: [
    { min: 0, max: 1.5, tone: 'low',
      riskLabel: { tr: 'Düşük', az: 'Aşağı', 'tr-CY': 'Düşük' },
      metric: { tr: 'PE olası değil', az: 'PE ehtimalsız', 'tr-CY': 'PE olası değil' },
      advice: { tr: 'D-dimer ile dışla; düşük olasılık.', az: 'D-dimer ilə istisna et; aşağı ehtimal.', 'tr-CY': 'D-dimer ile dışla; düşük olasılık.' } },
    { min: 2, max: 6, tone: 'mid',
      riskLabel: { tr: 'Orta', az: 'Orta', 'tr-CY': 'Orta' },
      metric: { tr: 'PE olası', az: 'PE ehtimallı', 'tr-CY': 'PE olası' },
      advice: { tr: 'D-dimer veya BT anjiyografi düşün.', az: 'D-dimer və ya KT anjioqrafiya düşün.', 'tr-CY': 'D-dimer veya BT anjiyografi düşün.' } },
    { min: 6.5, max: 12.5, tone: 'high',
      riskLabel: { tr: 'Yüksek', az: 'Yüksək', 'tr-CY': 'Yüksek' },
      metric: { tr: 'PE olası', az: 'PE ehtimallı', 'tr-CY': 'PE olası' },
      advice: { tr: 'BT pulmoner anjiyografi önerilir.', az: 'KT pulmoner anjioqrafiya tövsiyə olunur.', 'tr-CY': 'BT pulmoner anjiyografi önerilir.' } },
  ],
  references: ['Wells PS, et al. Derivation of a simple clinical model for PE. Thromb Haemost. 2000.'],
};
